### PR TITLE
Fix startup crash in the newest update

### PR DESCRIPTION
**Pull request by LifetimeMistake**
The newest Arma 3 update makes the server crash with an access violation exception on startup when using this tool.
For some reason changing BattlEye=true/false to BattlEye=1/0 makes it work again.

idk either

### CODE REVIEW

**Comment by LifetimeMistake** [comment]
Oops, accidentally pushed another commit regarding the mod browser to the wrong origin. If you choose to merge this, please cherrypick the first commit so that my changes to the mod browser don't get through

**Comment by igorkis-scrts** [comment]
Thanks for contribution!
I will test the app and will merge PR if everything is ok.

**Comment by LifetimeMistake** [comment]
Alright, I assume you're going to cherrypick the first commit then?
I can always re-PR without the bad commit.

**Comment by igorkis-scrts** [comment]
Yeah, do a re-PR or hard reset of branch with new commit.

**Comment by LifetimeMistake** [comment]
closing to re-PR

**Pull request closed without merging**
